import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import starlightOpenAPI, { createOpenAPISidebarGroup } from 'starlight-openapi';
import starlightLinksValidator from 'starlight-links-validator';

// Placeholder for the sidebar entries generated from `openapi.yaml`. Positioning
// this instead of hardcoding operation links keeps the sidebar correct when an
// operation is added or its `operationId` changes.
const openAPISidebarGroup = createOpenAPISidebarGroup();

export default defineConfig({
  site: 'https://mailapi.github.io',
  integrations: [
    starlight({
      title: 'Mail API',
      description: 'Vendor-neutral API specification for sending and receiving email.',
      favicon: '/mailapi-logo.png',
      logo: {
        src: './public/mailapi-logo.png',
        alt: 'Mail API logo'
      },
      components: {
        Sidebar: './src/components/Sidebar.astro'
      },
      social: [
        {
          icon: 'github',
          label: 'GitHub',
          href: 'https://github.com/mailapi/mailapi'
        }
      ],
      plugins: [
        starlightOpenAPI([
          {
            base: 'api',
            schema: './openapi.yaml',
            sidebar: {
              group: openAPISidebarGroup,
              label: 'Specification',
              collapsed: false,
              operations: { badges: true }
            }
          }
        ]),
        starlightLinksValidator({
          // starlight-openapi injects the /api/ routes rather than registering
          // content collection entries, so this plugin cannot see them. The
          // specification behind those pages is validated by `redocly lint`.
          exclude: ['/api/', '/api/**'],
          // Catch a full https://mailapi.github.io/... URL used where a
          // root-relative link belongs.
          sameSitePolicy: 'validate'
        })
      ],
      sidebar: [
        { label: 'Home', link: '/' },
        {
          label: 'Examples',
          items: [{ autogenerate: { directory: 'examples' } }]
        },
        {
          label: 'API',
          items: [
            openAPISidebarGroup,
            { label: 'Problem types', link: '/problems/' }
          ]
        },
        {
          // Listed explicitly rather than autogenerated: the reading order runs
          // from the request contract outward, which is not alphabetical.
          label: 'Concepts',
          items: [
            { label: 'Scope and capabilities', link: '/concepts/scope/' },
            { label: 'Authentication', link: '/concepts/authentication/' },
            { label: 'Submission responses', link: '/concepts/responses/' },
            { label: 'Idempotency', link: '/concepts/idempotency/' },
            { label: 'Versioning', link: '/concepts/versioning/' },
            { label: 'Design rationale', link: '/concepts/rationale/' }
          ]
        },
        {
          label: 'Implementations',
          items: [{ autogenerate: { directory: 'implementations' } }]
        },
        {
          label: 'Crosswalks',
          items: [
            {
              label: 'Protocols',
              items: [{ autogenerate: { directory: 'crosswalks/protocols' } }]
            },
            {
              label: 'Clouds',
              items: [{ autogenerate: { directory: 'crosswalks/clouds' } }]
            },
            {
              label: 'Languages',
              items: [{ autogenerate: { directory: 'crosswalks/languages' } }]
            },
            {
              label: 'Libraries',
              items: [{ autogenerate: { directory: 'crosswalks/libraries' } }]
            },
            {
              label: 'Frameworks',
              items: [{ autogenerate: { directory: 'crosswalks/frameworks' } }]
            },
            {
              label: 'Applications',
              items: [{ autogenerate: { directory: 'crosswalks/applications' } }]
            }
          ]
        }
      ]
    })
  ]
});
